// backend/seedPets.js
const path = require("path");
const sqlite3 = require("sqlite3").verbose();

const dbPath = path.join(__dirname, "petconnect.db");
const db = new sqlite3.Database(dbPath);

// 1) define the same pets array (plain JS, no TS types)
const pets = [
  {
    id: 1,
    name: "Luna",
    species: "Dog",
    breed: "Labrador Retriever",
    age: "2 years",
    size: "Large",
    gender: "Female",
    color: "Golden",
    energy: "High",
    goodWithKids: true,
    goodWithPets: true,
    description:
      "Friendly, outgoing, and always ready for an adventure. Luna loves playing fetch and splashing in water.",
    traits: ["Playful", "Affectionate", "House-trained"],
    location: "San Francisco, CA",
    shelter: "Golden Gate Animal Shelter",
    shelterId: 2,
    image: "https://images.pexels.com/photos/2253275/pexels-photo-2253275.jpeg",
    images: [
      "https://images.pexels.com/photos/2253275/pexels-photo-2253275.jpeg",
      "https://images.pexels.com/photos/1805164/pexels-photo-1805164.jpeg",
    ],
  },
  {
    id: 2,
    name: "Milo",
    species: "Cat",
    breed: "Domestic Short Hair",
    age: "1 year",
    size: "Small",
    gender: "Male",
    color: "Orange tabby",
    energy: "Medium",
    goodWithKids: true,
    goodWithPets: false,
    description:
      "Curious and confident, Milo loves window watching and chasing feather toys. Best as the only cat.",
    traits: ["Litter-trained", "Indoor-only", "Talkative"],
    location: "San Jose, CA",
    shelter: "Bay Area Cat Rescue",
    shelterId: 2,
    image: "https://images.pexels.com/photos/617278/pexels-photo-617278.jpeg",
    images: [
      "https://images.pexels.com/photos/617278/pexels-photo-617278.jpeg",
      "https://images.pexels.com/photos/1440387/pexels-photo-1440387.jpeg",
    ],
  },
  {
    id: 3,
    name: "Bella",
    species: "Dog",
    breed: "Beagle",
    age: "3 years",
    size: "Medium",
    gender: "Female",
    color: "Tricolor",
    energy: "Medium",
    goodWithKids: true,
    goodWithPets: true,
    description:
      "Gentle and sweet-natured, Bella enjoys sniffy walks and cuddle time on the couch.",
    traits: ["Leash-trained", "Crate-trained", "Good in car"],
    location: "Oakland, CA",
    shelter: "East Bay Rescue",
    shelterId: 2,
    image: "https://images.pexels.com/photos/5731867/pexels-photo-5731867.jpeg",
    images: [
      "https://images.pexels.com/photos/5731867/pexels-photo-5731867.jpeg",
      "https://images.pexels.com/photos/7210261/pexels-photo-7210261.jpeg",
    ],
  },

  // ---- new pets (4–12) from earlier answer ----
  {
    id: 4,
    name: "Max",
    species: "Dog",
    breed: "Border Collie",
    age: "10 months",
    size: "Medium",
    gender: "Male",
    color: "Black & white",
    energy: "High",
    goodWithKids: true,
    goodWithPets: true,
    description:
      "Smart and energetic pup who loves training games and agility-style play. Needs an active home.",
    traits: ["Very smart", "Needs exercise", "Knows basic cues"],
    location: "Berkeley, CA",
    shelter: "Golden Gate Animal Shelter",
    shelterId: 2,
    image: "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg",
    images: [
      "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg",
      "https://images.pexels.com/photos/977335/pexels-photo-977335.jpeg",
    ],
  },
  {
    id: 5,
    name: "Cleo",
    species: "Cat",
    breed: "Siamese Mix",
    age: "4 years",
    size: "Small",
    gender: "Female",
    color: "Seal point",
    energy: "Low",
    goodWithKids: false,
    goodWithPets: true,
    description:
      "A calm lap cat who bonds deeply with her people. Prefers a quiet home with predictable routines.",
    traits: ["Lap cat", "Quiet home", "Loves chin scratches"],
    location: "San Francisco, CA",
    shelter: "Bay Area Cat Rescue",
    shelterId: 2,
    image: "https://images.pexels.com/photos/20787/pexels-photo.jpg",
    images: [
      "https://images.pexels.com/photos/20787/pexels-photo.jpg",
      "https://images.pexels.com/photos/248280/pexels-photo-248280.jpeg",
    ],
  },
  {
    id: 6,
    name: "Rocky",
    species: "Dog",
    breed: "German Shepherd",
    age: "5 years",
    size: "Large",
    gender: "Male",
    color: "Black & tan",
    energy: "High",
    goodWithKids: true,
    goodWithPets: false,
    description:
      "Loyal and protective companion who has completed basic obedience. Best as the only dog.",
    traits: ["Obedience trained", "Loyal", "Active"],
    location: "San Mateo, CA",
    shelter: "East Bay Rescue",
    shelterId: 4,
    image: "https://images.pexels.com/photos/333083/pexels-photo-333083.jpeg",
    images: [
      "https://images.pexels.com/photos/333083/pexels-photo-333083.jpeg",
      "https://images.pexels.com/photos/4608239/pexels-photo-4608239.jpeg",
    ],
  },
  {
    id: 7,
    name: "Nala",
    species: "Cat",
    breed: "Maine Coon Mix",
    age: "2 years",
    size: "Medium",
    gender: "Female",
    color: "Brown tabby",
    energy: "Medium",
    goodWithKids: true,
    goodWithPets: true,
    description:
      "Fluffy, social cat who enjoys being around people and other friendly animals.",
    traits: ["Fluffy", "Social", "Litter-trained"],
    location: "San Jose, CA",
    shelter: "Bay Area Cat Rescue",
    shelterId: 4,
    image: "https://ziggyfamily.com/cdn/shop/files/reconnaitre-chat-croise-maine-coon_1000x.png?v=1743153946",
    images: [
      "https://ziggyfamily.com/cdn/shop/files/reconnaitre-chat-croise-maine-coon_1000x.png?v=1743153946",
      "https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg",
    ],
  },
  {
    id: 8,
    name: "Cooper",
    species: "Dog",
    breed: "Golden Retriever",
    age: "7 years",
    size: "Large",
    gender: "Male",
    color: "Golden",
    energy: "Medium",
    goodWithKids: true,
    goodWithPets: true,
    description:
      "Gentle senior who still enjoys daily walks and lots of affection. Great family dog.",
    traits: ["Senior", "Gentle", "House-trained"],
    location: "Walnut Creek, CA",
    shelter: "Golden Gate Animal Shelter",
    shelterId: 2,
    image: "https://images.all-free-download.com/images/graphiclarge/golden_retriever_dog_animal_221045.jpg",
    images: [
      "https://images.all-free-download.com/images/graphiclarge/golden_retriever_dog_animal_221045.jpg",
      "https://images.pexels.com/photos/2253275/pexels-photo-2253275.jpeg",
    ],
  },
  {
    id: 9,
    name: "Pepper",
    species: "Cat",
    breed: "Domestic Short Hair",
    age: "6 months",
    size: "Small",
    gender: "Female",
    color: "Black",
    energy: "High",
    goodWithKids: true,
    goodWithPets: true,
    description:
      "Playful kitten who loves wand toys and climbing cat trees. Would do well with another young cat.",
    traits: ["Kitten", "Playful", "Curious"],
    location: "Oakland, CA",
    shelter: "Bay Area Cat Rescue",
    shelterId: 2,
    image: "https://images.pexels.com/photos/1276553/pexels-photo-1276553.jpeg",
    images: [
      "https://images.pexels.com/photos/1276553/pexels-photo-1276553.jpeg",
      "https://images.pexels.com/photos/1643457/pexels-photo-1643457.jpeg",
    ],
  },
  {
    id: 10,
    name: "Bruno",
    species: "Dog",
    breed: "Mixed Breed",
    age: "1.5 years",
    size: "Medium",
    gender: "Male",
    color: "Brindle",
    energy: "High",
    goodWithKids: false,
    goodWithPets: true,
    description:
      "Goofy, active dog who loves hikes and puzzle toys. Best in an adults-only home.",
    traits: ["Goofy", "Active", "Food-motivated"],
    location: "San Francisco, CA",
    shelter: "East Bay Rescue",
    shelterId: 2,
    image: "https://images.pexels.com/photos/7210261/pexels-photo-7210261.jpeg",
    images: [
      "https://images.pexels.com/photos/7210261/pexels-photo-7210261.jpeg",
      "https://images.pexels.com/photos/5731867/pexels-photo-5731867.jpeg",
    ],
  },
  {
    id: 11,
    name: "Willow",
    species: "Cat",
    breed: "Russian Blue Mix",
    age: "8 years",
    size: "Small",
    gender: "Female",
    color: "Gray",
    energy: "Low",
    goodWithKids: true,
    goodWithPets: false,
    description:
      "Calm senior cat who loves sunny windowsills and soft beds. Perfect for a relaxed home.",
    traits: ["Senior", "Low-maintenance", "Quiet"],
    location: "San Jose, CA",
    shelter: "Bay Area Cat Rescue",
    shelterId: 2,
    image: "https://cdn-fastly.petguide.com/media/2022/02/16/8202994/russian-blue.jpg?size=720x845&nocrop=1",
    images: [
      "https://cdn-fastly.petguide.com/media/2022/02/16/8202994/russian-blue.jpg?size=720x845&nocrop=1",
      "https://images.pexels.com/photos/617278/pexels-photo-617278.jpeg",
    ],
  },
  {
    id: 12,
    name: "Duke",
    species: "Dog",
    breed: "Boxer",
    age: "4 years",
    size: "Large",
    gender: "Male",
    color: "Fawn",
    energy: "High",
    goodWithKids: true,
    goodWithPets: true,
    description:
      "Bouncy, social dog who loves people and other friendly dogs. Great for an active family.",
    traits: ["Social", "House-trained", "Knows sit & stay"],
    location: "Fremont, CA",
    shelter: "Golden Gate Animal Shelter",
    shelterId: 2,
    image: "https://images.pexels.com/photos/264005/pexels-photo-264005.jpeg",
    images: [
      "https://images.pexels.com/photos/264005/pexels-photo-264005.jpeg",
      "https://images.pexels.com/photos/4608239/pexels-photo-4608239.jpeg",
    ],
  },
  {
  id: 13,
  name: "Thumper",
  species: "Rabbit",
  breed: "Mini Lop",
  age: "2 years",
  size: "Small",
  gender: "Male",
  color: "White & gray",
  energy: "Medium",
  goodWithKids: true,
  goodWithPets: true,
  description:
    "Gentle rabbit who enjoys leafy greens and quiet time in a cozy hideout. Litter-trained for indoor living.",
  traits: ["Litter-trained", "Gentle", "Indoor only"],
  location: "San Francisco, CA",
  shelter: "Small Paws Rescue",
  shelterId: 4,
  image: "https://images.pexels.com/photos/247373/pexels-photo-247373.jpeg",
  images: [
    "https://images.pexels.com/photos/247373/pexels-photo-247373.jpeg",
    "https://images.pexels.com/photos/20787/pexels-photo.jpg",
  ],
},
{
  id: 14,
  name: "Kiwi",
  species: "Bird",
  breed: "Parakeet",
  age: "1 year",
  size: "Small",
  gender: "Female",
  color: "Green & yellow",
  energy: "High",
  goodWithKids: true,
  goodWithPets: true,
  description:
    "Chatty little parakeet who loves chirping along to music and exploring her play gym.",
  traits: ["Vocal", "Hand-tame", "Loves toys"],
  location: "San Jose, CA",
  shelter: "Feathered Friends Sanctuary",
  shelterId: 2,
  image: "https://w0.peakpx.com/wallpaper/12/124/HD-wallpaper-birds-rose-ringed-parakeet-bird.jpg",
  images: [
    "https://w0.peakpx.com/wallpaper/12/124/HD-wallpaper-birds-rose-ringed-parakeet-bird.jpg",
    "https://images.pexels.com/photos/677414/pexels-photo-677414.jpeg",
  ],
},
{
  id: 15,
  name: "Pip",
  species: "Guinea Pig",
  breed: "American",
  age: "8 months",
  size: "Small",
  gender: "Male",
  color: "Brown & white",
  energy: "Medium",
  goodWithKids: true,
  goodWithPets: true,
  description:
    "Very social guinea pig who loves veggie snacks and chatting with gentle humans.",
  traits: ["Social", "Good for beginners", "Vocal"],
  location: "Oakland, CA",
  shelter: "Small Paws Rescue",
  shelterId: 4,
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaffzFNTgRFIF7HZizXNTtQEbsJH01Mv93rA&s",
  images: [
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaffzFNTgRFIF7HZizXNTtQEbsJH01Mv93rA&s",
    "https://images.pexels.com/photos/7474470/pexels-photo-7474470.jpeg",
  ],
},
{
  id: 16,
  name: "Mango",
  species: "Lizard",
  breed: "Bearded Dragon",
  age: "3 years",
  size: "Medium",
  gender: "Male",
  color: "Sand",
  energy: "Low",
  goodWithKids: true,
  goodWithPets: false,
  description:
    "Calm bearded dragon who enjoys basking and hand-feeding time. Great for a reptile-loving family.",
  traits: ["Reptile experience preferred", "Calm", "Hand-fed"],
  location: "Berkeley, CA",
  shelter: "Reptile Haven",
  shelterId: 2,
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTh3ix6RLe32GJ2RYfLrHgNS6fnplNCPp5H_Q&s",
  images: [
    "https://images.pexels.com/photos/6752514/pexels-photo-6752514.jpeg",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuDopFNmBGXceQungb1H_qA6I8eB7c_SBe-A&s",
  ],
},
{
  id: 17,
  name: "Snowball",
  species: "Rabbit",
  breed: "Lionhead",
  age: "1 year",
  size: "Small",
  gender: "Female",
  color: "White",
  energy: "Medium",
  goodWithKids: true,
  goodWithPets: true,
  description:
    "Sweet rabbit who loves gentle petting and crunchy veggies. Litter-trained for indoor living.",
  traits: ["Litter-trained", "Gentle", "Indoor only"],
  location: "San Francisco, CA",
  shelter: "Small Paws Rescue",
  shelterId: 4,
  image: "https://images.pexels.com/photos/247373/pexels-photo-247373.jpeg",
  images: [
    "https://images.pexels.com/photos/247373/pexels-photo-247373.jpeg",
    "https://images.pexels.com/photos/3828094/pexels-photo-3828094.jpeg",
  ],
},
{
  id: 18,
  name: "Rio",
  species: "Bird",
  breed: "Cockatiel",
  age: "3 years",
  size: "Small",
  gender: "Male",
  color: "Gray & yellow",
  energy: "High",
  goodWithKids: true,
  goodWithPets: true,
  description:
    "Friendly cockatiel who whistles tunes and enjoys shoulder time with his people.",
  traits: ["Whistles", "Hand-tame", "Loves interaction"],
  location: "San Jose, CA",
  shelter: "Feathered Friends Sanctuary",
  shelterId: 2,
  image: "https://thumbs.dreamstime.com/b/pied-cockatiel-1973429.jpg",
  images: [
    "https://thumbs.dreamstime.com/b/pied-cockatiel-1973429.jpg",
    "https://feistyfeathers.com/wp-content/uploads/2016/03/tiel03_pied.jpg?w=640",
  ],
},
{
  id: 19,
  name: "Hazel",
  species: "Guinea Pig",
  breed: "Abyssinian",
  age: "2 years",
  size: "Small",
  gender: "Female",
  color: "Brown & white",
  energy: "Medium",
  goodWithKids: true,
  goodWithPets: true,
  description:
    "Curious guinea pig who loves tunnels, hay, and gentle laps. Best with another friendly piggy.",
  traits: ["Social", "Good for beginners", "Vocal"],
  location: "Oakland, CA",
  shelter: "Small Paws Rescue",
  shelterId: 4,
  image: "https://cdn.shopify.com/s/files/1/0530/3762/9610/files/Abyssinian_Guinea_Pig_on_fleece_1024x1024.png?v=1684489159",
  images: [
    "https://cdn.shopify.com/s/files/1/0530/3762/9610/files/Abyssinian_Guinea_Pig_on_fleece_1024x1024.png?v=1684489159",
    "https://i.pinimg.com/474x/90/de/33/90de339e4b6dd927cb14e8bcdf666cb7.jpg",
  ],
},
{
  id: 20,
  name: "Pebble",
  species: "Turtle",
  breed: "Red-Eared Slider",
  age: "5 years",
  size: "Medium",
  gender: "Male",
  color: "Green",
  energy: "Low",
  goodWithKids: true,
  goodWithPets: false,
  description:
    "Relaxed turtle who enjoys basking under his heat lamp and swimming in a roomy tank.",
  traits: ["Aquatic", "Low-maintenance", "Reptile experience helpful"],
  location: "Berkeley, CA",
  shelter: "Reptile Haven",
  shelterId: 2,
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmgxZPYIGqwzAAZ4LbjF0p3B1QfkQuIx_I5w&s",
  images: [
    "https://images.pexels.com/photos/4588474/pexels-photo-4588474.jpeg",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9_2Yk1",
  ],
}

];

// 2) create table + insert
db.serialize(() => {
  db.run(`
    CREATE TABLE IF NOT EXISTS pets (
      id INTEGER PRIMARY KEY,
      name TEXT NOT NULL,
      species TEXT NOT NULL,
      breed TEXT NOT NULL,
      age TEXT NOT NULL,
      size TEXT NOT NULL,
      gender TEXT NOT NULL,
      color TEXT NOT NULL,
      energy TEXT NOT NULL,
      goodWithKids INTEGER NOT NULL,
      goodWithPets INTEGER NOT NULL,
      description TEXT NOT NULL,
      traits TEXT NOT NULL,
      location TEXT NOT NULL,
      shelter TEXT NOT NULL,
      shelterId INTEGER NOT NULL,
      image TEXT NOT NULL,
      images TEXT NOT NULL
    );
  `);

  const stmt = db.prepare(`
    INSERT OR REPLACE INTO pets (
      id, name, species, breed, age, size, gender, color, energy,
      goodWithKids, goodWithPets, description, traits, location,
      shelter, shelterId, image, images
    ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
  `);

  pets.forEach((pet) => {
    stmt.run(
      pet.id,
      pet.name,
      pet.species,
      pet.breed,
      pet.age,
      pet.size,
      pet.gender,
      pet.color,
      pet.energy,
      pet.goodWithKids ? 1 : 0,
      pet.goodWithPets ? 1 : 0,
      pet.description,
      JSON.stringify(pet.traits),
      pet.location,
      pet.shelter,
      pet.shelterId,
      pet.image,
      JSON.stringify(pet.images)
    );
  });

  stmt.finalize(() => {
    console.log(`Inserted/updated ${pets.length} pets.`);
    db.close();
  });
});
